-- return {
--   {
--     "gthelding/monokai-pro.nvim",
--     config = function()
--       require("monokai-pro").setup({
--         filter = "ristretto",
--         override = function()
--           return {
--             -- Mini Icons
--             NonText = { fg = "#948a8b" },
--             MiniIconsGrey = { fg = "#948a8b" },
--             MiniIconsRed = { fg = "#fd6883" },
--             MiniIconsBlue = { fg = "#85dacc" },
--             MiniIconsGreen = { fg = "#adda78" },
--             MiniIconsYellow = { fg = "#f9cc6c" },
--             MiniIconsOrange = { fg = "#f38d70" },
--             MiniIconsPurple = { fg = "#a8a9eb" },
--             MiniIconsAzure = { fg = "#a8a9eb" },
--             MiniIconsCyan = { fg = "#85dacc" },
--             -- Line numbers - more visible
--             LineNr = { fg = "#72696a" },
--             CursorLineNr = { fg = "#f9cc6c", bold = true },
--             -- Neo-tree improvements
--             NeoTreeDimText = { fg = "#948a8b" },
--             NeoTreeGitIgnored = { fg = "#72696a" },
--             NeoTreeDotfile = { fg = "#948a8b" },
--             NeoTreeIndentMarker = { fg = "#5b5353" },
--             NeoTreeExpander = { fg = "#c3b7b8" },
--           }
--         end,
--       })
--       vim.cmd([[colorscheme monokai-pro]])
--     end,
--   },
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "monokai-pro",
--     },
--   },
-- }
